### PR TITLE
2018-01-26-introducing-elm-to-react-developers

### PR DESCRIPTION
**Pull request by n1k0**
Work in progress.

### CODE REVIEW

**Comment by n1k0** [comment]
I think it's ready for review now. Preview is available at https://github.com/allo-media/tech-blog/blob/8b8b8fe3972182e9ff21ae72b55d016a54c00e02/_posts/2018-01-26-introducing-elm-to-redux-users.markdown

**Comment by vjousse** [comment]
This is great work. Love the Ferris Wheel!
One thing that could be improved to me, is to state the point of the article more clearly. At first I thought you would explain what a `foldl` is, and at the end of the article I was under the impression that you were introducing The Elm Architecture compared to what's done in Redux (and could imply, indeed, some `foldl` usage).
Keep in mind that it's Saturday and I'm maybe just not fully awake ^^

**Comment by n1k0** [comment]
This is not much more of an anecdote, with a few observations and toss at
the end of the article. Not sure if we should turn an anecdote into a full
blown structured theoretical essay.

The idea here was to quickly draft something publishable without spending
days on establishing a top notch structuration, but maybe that's a wrong
approach, especially if it's more coding than useful.

Do you have suggestions how it could be revamped to more efficiently convey
usefulness?

Le 27 janv. 2018 12:08, "Vincent Jousse" <notifications@github.com> a
écrit :

**Comment by n1k0** [comment]
Added *This is a short anecddote about how I approached teaching things to someone else.* as an introduction and renamed blog post title to *Reduce and the Ferris wheel metaphor*.

**Comment by vjousse** [comment]
You're right, presenting the article as an anecdote is good to me 👍

**Comment by n1k0** [comment]
We have a first version available at https://allo-media.github.io/tech-blog/elm/react/javascript/2018/01/26/reduce-and-the-ferris-wheel-metaphor.html.

I'm landing this, we can always iterate in next PRs.

**Pull request merged**
